### ISSUE TITLE
Option to hide Small Treasure Chests

### ISSUE THREAD

**Issue by amiyuy** [kemayo/wow-handynotes-battleforazerothtreasures#10]
Request: Add option to hide Small Treasure Chests

Small Treasure Chests seem to be random spawns, yet they're showing up on my world map.  I would prefer they not be there as it's cluttery.  If it is spawned, it shows up on my minimap already, I don't want to go out of my way for something that might not be there.

Thanks.

**Comment by kemayo** [comment]
There's already an option. It's in the settings for "junk" -- if you uncheck "show junk", these chests won't be displayed. (This is also the default, but that might not have gotten updated somewhere along the way.)
