### ISSUE TITLE
Can't mount in Mechagon

### ISSUE THREAD

**Issue by fhantum** [kemayo/wow-handynotes-battleforazerothtreasures#15]
Unable to mount in Mechagon when handy notes is active. Day 2 that this has happened to me.

**Comment by kemayo** [comment]
Can’t say I’ve seen this happen personally. Is it this handynotes plugin specifically, or all of handynotes?

**Comment by MysticalOS** [comment]
That's the stuck in combat bug and not related to addons in any shape or form. Plenty of threads on it and even some blue post responses.
