### ISSUE TITLE
Suggestion: In The Belly of the Jelly/Ravenous Slimes support

### ISSUE THREAD

**Issue by rainkius** [kemayo/wow-handynotes-battleforazerothtreasures#23]
Below are (what should be) all associated QuestIDs, ItemIDs, Achievement etc. Details on feeding the slimes are here if needed: https://www.wowhead.com/achievement=13715/from-the-belly-of-the-jelly#comments:id=3126516

I created a blue and grey version of an icon that could be used to mark them, attached below (as png since they don't support blp). Please don't feel obligated to use them; I made them when I was under the delusion I could somehow write this plugin myself. Haha e_e

![RS_Grey](https://user-images.githubusercontent.com/53383516/62000304-c7cf8500-b0a1-11e9-86ce-9a4a66df3829.png)
![RS_Blue](https://user-images.githubusercontent.com/53383516/62000305-c7cf8500-b0a1-11e9-8500-d9df527ca40a.png)

For me, a very basic "icon gone once slime is fed" functionality would be great.

 Thank you :) 

ETA: Weekly quest associated with each slime & the name/spell ID of buff from item.

----

Nazjatar MapID: 1355

Ravenous Slime 1:
32.76 39.53
Daily Quest ID: 55430
Weekly Quest ID: 55473
NPC ID: 151875 

Ravenous Slime 2:
45.70 24.11 
Daily Quest ID: 55429
Weekly Quest ID: 55472
NPC ID: 151874 

Ravenous Slime 3:
54.90 48.70
Daily Quest ID: 55427
Weekly Quest ID: 55470
NPC ID: 151218 

Ravenous Slime 4:
71.71 25.70
Daily Quest ID: 55428
Weekly Quest ID: 55471
NPC ID: 151782

**_REQUIRED ITEM:_**
Prismatic Crystal
ItemID: 167893

Spell Name: Prismatic Hypnosis
SpellID: 293404

**_REWARDS:_**  
_(Random, can get duplicates)_
Slimy Darkhunter
SpeciesID: 2762
ItemID: 167809

Slimy Eel
SpeciesID: 2758
ItemID: 167808

Slimy Fangtooth
SpeciesID: 2761
ItemID: 167807

Slimy Hermit Crab
SpeciesID: 2763
ItemID: 167810

Slimy Octopode
SpeciesID: 2760
ItemID: 167806

Slimy Otter
SpeciesID: 2757
ItemID: 167805

Slimy Sea Slug
SpeciesID: 2765
ItemID: 167804

**_RELATED ACHIEVEMENT:_**
From The Belly Of The Jelly
AchievementID: 13715

**Comment by kemayo** [comment]
I'm going to admit, that took me way too long.
