### ISSUE TITLE
Shadowlands Pre-Patch Error (Achievemens_Handler)

### ISSUE THREAD

**Issue by Meebsy** [kemayo/wow-handynotes-battleforazerothtreasures#28]
`5x ...s\HandyNotes_BattleForAzerothAchievments_Handler.lua:58: attempt to call global 'GetAtlasInfo' (a nil value)
[string "@HandyNotes_BattleForAzerothAchievments\HandyNotes_BattleForAzerothAchievments_Handler.lua"]:58: in function <...s\HandyNotes_BattleForAzerothAchievments_Handler.lua:57>
[string "@HandyNotes_BattleForAzerothAchievments\HandyNotes_BattleForAzerothAchievments_Handler.lua"]:115: in function <...s\HandyNotes_BattleForAzerothAchievments_Handler.lua:112>
[string "@HandyNotes_BattleForAzerothAchievments\HandyNotes_BattleForAzerothAchievments_Handler.lua"]:179: in function <...s\HandyNotes_BattleForAzerothAchievments_Handler.lua:176>
[string "@HandyNotes_BattleForAzerothAchievments\HandyNotes_BattleForAzerothAchievments_Handler.lua"]:408: in function `(for generator)'
[string "@HandyNotes\HandyNotes-v1.6.0.lua"]:433: in function <HandyNotes\HandyNotes.lua:419>
[string "=[C]"]: ?
[string "@HandyNotes\HandyNotes-v1.6.0.lua"]:56: in function <HandyNotes\HandyNotes.lua:51>
[string "@HandyNotes\HandyNotes-v1.6.0.lua"]:483: in function `?'
[string "@ElvUI\Libraries\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...ies\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@ElvUI\Libraries\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...ies\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@ElvUI\Libraries\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@TomTom\libs\HereBeDragons\HereBeDragons-2.0-14.lua"]:269: in function <...dOns\TomTom\libs\HereBeDragons\HereBeDragons-2.0.lua:252>
[string "@TomTom\libs\HereBeDragons\HereBeDragons-2.0-14.lua"]:299: in function <...dOns\TomTom\libs\HereBeDragons\HereBeDragons-2.0.lua:298>`
Not sure what caused it to happen except that it happened when I opened the world map.

**Comment by Meebsy** [comment]
`1x ...s\HandyNotes_BattleForAzerothAchievments_Handler.lua:393: attempt to index upvalue 'WorldMapTooltip' (a nil value)
[string "@HandyNotes_BattleForAzerothAchievments\HandyNotes_BattleForAzerothAchievments_Handler.lua"]:393: in function <...s\HandyNotes_BattleForAzerothAchievments_Handler.lua:391>
[string "=[C]"]: ?
[string "@HandyNotes\HandyNotes-v1.6.0.lua"]:56: in function <HandyNotes\HandyNotes.lua:51>
[string "@HandyNotes\HandyNotes-v1.6.0.lua"]:169: in function `OnLeave'
[string "@HandyNotes\HandyNotes-v1.6.0.lua"]:393: in function <HandyNotes\HandyNotes.lua:392>`
This one came from mousing over an icon for a BFA achievment that I hadn't completed.

**Comment by Meebsy** [comment]
`8x ...ts\HandyNotes_BattleForAzerothAchievments_Config.lua:152: attempt to call global 'IsQuestFlaggedCompleted' (a nil value)
[string "@HandyNotes_BattleForAzerothAchievments\HandyNotes_BattleForAzerothAchievments_Config.lua"]:152: in function <...ts\HandyNotes_BattleForAzerothAchievments_Config.lua:143>
[string "@HandyNotes_BattleForAzerothAchievments\HandyNotes_BattleForAzerothAchievments_Config.lua"]:182: in function `should_show_point'
[string "@HandyNotes_BattleForAzerothAchievments\HandyNotes_BattleForAzerothAchievments_Handler.lua"]:407: in function `(for generator)'
[string "@HandyNotes\HandyNotes-v1.6.0.lua"]:433: in function <HandyNotes\HandyNotes.lua:419>
[string "=[C]"]: ?
[string "@HandyNotes\HandyNotes-v1.6.0.lua"]:56: in function <HandyNotes\HandyNotes.lua:51>
[string "@HandyNotes\HandyNotes-v1.6.0.lua"]:483: in function `?'
[string "@ElvUI\Libraries\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...ies\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@ElvUI\Libraries\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...ies\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@ElvUI\Libraries\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@TomTom\libs\HereBeDragons\HereBeDragons-2.0-14.lua"]:269: in function <...dOns\TomTom\libs\HereBeDragons\HereBeDragons-2.0.lua:252>
[string "@TomTom\libs\HereBeDragons\HereBeDragons-2.0-14.lua"]:299: in function <...dOns\TomTom\libs\HereBeDragons\HereBeDragons-2.0.lua:298>`
Not a Achievements_Handler error but thought I would post it here with other errors I found.

**Comment by kemayo** [comment]
You're filing this issue on the wrong addon. This github is for [this one](https://www.curseforge.com/wow/addons/handynotes-battle-for-azeroth-treasures), which doesn't contain any of the files your errors are referencing.

I can't actually find `HandyNotes_BattleForAzerothAchievments`, so I have no idea where you should go for it. 🤷
