### ISSUE TITLE
Boralus treasure "Secret of the Depths" missing

### ISSUE THREAD

**Issue by cremor** [kemayo/wow-handynotes-battleforazerothtreasures#3]
This involves multiple loations in Boralus, see https://www.wowhead.com/achievement=12852/treasures-of-tiragarde-sound#english-comments

**Comment by kemayo** [comment]
Hey, handy, last time I looked that wasn't filled out. I'll go work out the questids for it.

**Comment by kemayo** [comment]
As we may see from 034f36b171ca5a46f6aaec40f17265c04ceb8375, that was more complicated to add than I expected.
