### ISSUE TITLE
Uldum: Friendly Alpaca Progress Tracker

### ISSUE THREAD

**Issue by gitarrg** [kemayo/wow-handynotes-battleforazerothtreasures#33]
Hi there,

Might be nice to add a progress tracker (similar to eg.: the Korthia Mounts: Darkmoul or Malie) to the Friendly Alpaca in Uldum.

could be done like this:
```diff
3a4,12
> -- Friendly Alpaca
> local function GetFriendlyAlpaceStatus()
>     local count = select(4, GetQuestObjectiveInfo(58881, 0, false))
>     if count ~= nil then
>         return format(" (%d/7)", count)
>     end
>     return ""
> end
>
22c31
<     note="Feed it {item:174858:Gersahl Greens} for 7 days; find them by the rivers",
---
>     note="Feed it {item:174858:Gersahl Greens} for 7 days; find them by the rivers" .. GetFriendlyAlpaceStatus(),
```

Screenshot how this change looks for me in game:
![image](https://user-images.githubusercontent.com/82116652/149625842-74459178-774c-4139-9ce6-320cb3c1103f.png)

**Comment by kemayo** [comment]
I agree it's a good idea -- I'll add it, but in a slightly different way than suggested, after I update the handler with the Shadowlands changes.
