### ISSUE TITLE
Icon elit and chest doesnt disappear

### ISSUE THREAD

**Issue by FitzcairnHS** [kemayo/wow-handynotes-battleforazerothtreasures#4]
Hi, the addon is great and work perfectly when you're solo or duo but when you are more in the group the elite's icon and the chest doesn't disappear on the mini map and you have to open the big map and click on it to hide.

**Comment by kemayo** [comment]
Do they disappear if you reload your UI, or do they stick around through that?

**Comment by Sembiance** [comment]
The Rare NPC's are not disappearing because you need to modify config.lua and add the following to line 142:
```
local player_name = UnitName("player")
```

Basically player_name was not being declared, so later on this section of code never evaluated to true:
```
local _, _, completed, _, _, completedBy = GetAchievementCriteriaInfoByID(point.achievement, point.criteria)
if completed and completedBy == player_name then
```

**Comment by kemayo** [comment]
@Sembiance That's a different issue, and has already been fixed. Though I guess I haven't done a proper release for it, so I should do that.

**Comment by FitzcairnHS** [comment]
I did a reload but the skull icon on the minimap and large map is still there when we are in group of 3. The weird thing is that's working perfectly when i'm alone or in group of 2. It begin to bug only with 3 people in the groupe. Really strange.

**Comment by kemayo** [comment]
Hmmm. Can you check whether you got the achievement credit for it? (In the Adventurer / Treasures achievement for whichever zone you’re in.)

If you did, that’d suggest it’s just related to the tracking quest for the mob/chest... and I’d become interested in whether you could go loot the mob again without waiting for a world quest.

Since I do know the criteria for almost everything, I could probably make that more authoritative for considering completion.

**Comment by FitzcairnHS** [comment]
So we did loot the mob again and we got the achievement but the skill is still there. The thing i don't understand is why it's working alone or with two people but it's not working with several people in the groupe. We have to hide it manually each time we play in groupe.

Because we are 3 irl friend who do the quest it's happen everytime. When the third one is not online and that we play only me and a friend it's working fine.

**Comment by FitzcairnHS** [comment]
Hey, i just seen you did an update today and it seems working perfectly now even in a group of three so thanks you for your work ! :) 
👍

**Comment by kemayo** [comment]
Don't honestly know what I did there that might have fixed it, but I won't complain!

**Comment by FitzcairnHS** [comment]
:D
